name: CI - Dependency Checker

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install security tools
      run: |
        pip install pip-audit safety

    - name: Run tests
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        pytest tests/

    - name: Run pip-audit
      run: |
        pip-audit -r requirements.txt -f json -o pip_audit_report.json

    - name: Run safety
      run: |
        safety check -r requirements.txt --json > safety_report.json

    - name: Generate audit report
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        python audit/report_generator.py

    - name: Upload audit artifacts
      uses: actions/upload-artifact@v4
      with:
        name: audit-reports
        path: |
          pip_audit_report.json
          safety_report.json
          audit_report.json
          audit_report.md

    - name: Run audit script
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPO_OWNER: ${{ github.repository_owner }}
        GITHUB_REPO_NAME: ${{ github.event.repository.name }}
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        python github/github_action_runner.py
